env:
  global:
    - CC_TEST_REPORTER_ID=323cb9fbdd4915f4bdb1734a71cb0d65c75dcdd5a2e724d51e422c4683367b54

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - coverage xml
  - ./cc-test-reporter after-build -t coverage.py --exit-code $TRAVIS_TEST_RESULT

language: python
sudo: required
dist: xenial

python:
  - "3.5"
  - "3.6"
  - "3.7"

# Install Requirements
install: "pip install -r requirements.txt"

# Run tests
script:
  - coverage run --source='.' manage.py test -v 2
