service: django-notifs-sqs-lambda-worker
frameworkVersion: '2'
useDotenv: true

provider:
  name: aws
  runtime: python3.9
  lambdaHashingVersion: '20201221'
  environment:
    DJANGO_SETTINGS_MODULE: ${env:DJANGO_SETTINGS_MODULE}
    NOTIFICATIONS_PUSHER_URL: ${env:NOTIFICATIONS_PUSHER_URL}

constructs:
  jobs:
    type: queue
    worker:
      handler: handler.consumer

plugins:
  - serverless-lift
  - serverless-python-requirements
package:
  patterns:
    - '!node_modules/**'
