# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='source_display_name',
            field=models.CharField(default='Osaetin Daniel', max_length=150),
            preserve_default=False,
        ),
    ]
