# Generated by Django 3.1.7 on 2021-03-13 19:00

import django
from django.db import migrations
import notifications.fields

from django.db.models import JSONField


django_version = django.get_version()
django_version = float(django_version[::-1].replace('.', '', 1)[::-1])

if django_version < 3.1:
    from django_jsonfield_backport.models import JSONField  # noqa


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_squashed_0010_notification_channels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='channels',
            field=notifications.fields.ListField(max_length=200),
        ),
        migrations.AlterField(
            model_name='notification',
            name='extra_data',
            field=JSONField(default=dict),
        ),
    ]
