# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 11:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_auto_20170719_1138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('-id',)},
        ),
    ]
