# Generated by Django 2.2 on 2021-08-22 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_rename_channels_json_to_channels'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='obj',
            new_name='object_id',
        ),
    ]
